version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password!
      MYSQL_DATABASE: testdb
      MYSQL_USER: khzhao
      MYSQL_PASSWORD: password!
    ports:
      - "3306:3306"
    volumes:
      - /home/khzhao/test/mysql_data:/var/lib/mysql

  node:
    build: .
    container_name: node
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: khzhao
      DB_PASSWORD: password!
      DB_NAME: testdb
    command: sh -c "dockerize -wait tcp://mysql:3306 -timeout 20s npm start"
